const Teacher = require('../models/Teacher');
const Settlement = require('../models/Settlement');
const { generateSettlement, computeSettlementLines } = require('../services/settlementService');

const POPULATE = [
  { path: 'teacher' },
  { path: 'lines.student', select: 'name' },
  { path: 'lines.instrument' },
  { path: 'lines.plan' },
];

async function generate(req, res) {
  const { teacherId, periodMonth, periodYear } = req.body;
  if (!teacherId || !periodMonth || !periodYear) {
    return res.status(400).json({ message: 'Profesor, mes y año son requeridos' });
  }

  const teacher = await Teacher.findById(teacherId);
  if (!teacher) return res.status(404).json({ message: 'Profesor no encontrado' });

  const settlement = await generateSettlement(teacher, Number(periodMonth), Number(periodYear));
  const populated = await Settlement.findById(settlement._id).populate(POPULATE);
  res.json(populated);
}

async function list(req, res) {
  const { periodMonth, periodYear, teacherId } = req.query;
  const filter = {};
  if (periodMonth) filter.periodMonth = Number(periodMonth);
  if (periodYear) filter.periodYear = Number(periodYear);
  if (teacherId) filter.teacher = teacherId;

  const settlements = await Settlement.find(filter).populate(POPULATE).sort({ periodYear: -1, periodMonth: -1 });

  // A settlement whose teacher was hard-deleted has nothing useful to show —
  // a dangling "Profesor eliminado" row is more confusing than helpful here,
  // so clean it up instead of surfacing it.
  const orphaned = settlements.filter((s) => !s.teacher);
  if (orphaned.length > 0) {
    await Settlement.deleteMany({ _id: { $in: orphaned.map((s) => s._id) } });
  }

  res.json(settlements.filter((s) => s.teacher));
}

async function getOne(req, res) {
  const settlement = await Settlement.findById(req.params.id).populate(POPULATE);
  if (!settlement) return res.status(404).json({ message: 'No encontrado' });
  res.json(settlement);
}

// Lets the admin correct which teacher/period a settlement belongs to (e.g. it
// was generated by mistake for the wrong month). Since the lines were computed
// against the OLD teacher+period, they're recomputed for the new identity —
// otherwise the row would show a corrected label next to stale numbers.
async function updateIdentity(req, res, existing) {
  const { teacherId, periodMonth, periodYear } = req.body;
  const newTeacherId = teacherId || existing.teacher.toString();
  const newMonth = periodMonth != null ? Number(periodMonth) : existing.periodMonth;
  const newYear = periodYear != null ? Number(periodYear) : existing.periodYear;

  const teacher = await Teacher.findById(newTeacherId);
  if (!teacher) return res.status(404).json({ message: 'Profesor no encontrado' });

  const duplicate = await Settlement.findOne({
    _id: { $ne: existing._id },
    teacher: newTeacherId,
    periodMonth: newMonth,
    periodYear: newYear,
  });
  if (duplicate) {
    return res.status(409).json({ message: 'Ya existe una liquidación para ese profesor y período' });
  }

  const { lines, totalAmount } = await computeSettlementLines(teacher, newMonth, newYear);
  existing.teacher = newTeacherId;
  existing.periodMonth = newMonth;
  existing.periodYear = newYear;
  existing.lines = lines;
  existing.totalAmount = totalAmount;
  existing.generatedAt = new Date();
  await existing.save();

  const populated = await Settlement.findById(existing._id).populate(POPULATE);
  res.json(populated);
}

// Lets the admin correct a generated line by hand (a negotiated rate, a partial
// month, etc.) — the total is always recomputed server-side from pricePerClass
// and classesCount, never trusted from the client.
async function update(req, res) {
  const { lines, teacherId, periodMonth, periodYear } = req.body;

  if (teacherId || periodMonth != null || periodYear != null) {
    const existing = await Settlement.findById(req.params.id);
    if (!existing) return res.status(404).json({ message: 'No encontrado' });
    return updateIdentity(req, res, existing);
  }

  if (!Array.isArray(lines)) {
    return res.status(400).json({ message: 'Las líneas son requeridas' });
  }

  const normalizedLines = lines.map((line) => ({
    ...line,
    total: Number(line.pricePerClass) * Number(line.classesCount),
  }));
  const totalAmount = normalizedLines.reduce((sum, l) => sum + l.total, 0);

  const settlement = await Settlement.findByIdAndUpdate(
    req.params.id,
    { lines: normalizedLines, totalAmount },
    { new: true, runValidators: true }
  ).populate(POPULATE);
  if (!settlement) return res.status(404).json({ message: 'No encontrado' });
  res.json(settlement);
}

async function remove(req, res) {
  const settlement = await Settlement.findByIdAndDelete(req.params.id);
  if (!settlement) return res.status(404).json({ message: 'No encontrado' });
  res.json({ message: 'Eliminado' });
}

module.exports = { generate, list, getOne, update, remove };
